First version of the README.md
doka-guide/action-labeler pull request #1
Opened 2021-11-30 21:27 UTC by nlopin

2021-12-01 10:42 UTC, igsekor requested changes

2021-12-01 12:35 UTC, igsekor requested changes

2021-12-01 12:35 UTC, igsekor commented on README.md
> +
```suggestion

For all labels there is an opportunity to setup the strategy of labelling. There are four options:

- `merge-with-others` — for merging the new list of labels after pushing and the old list before update (default - true);
- `completely-update` — for reset the list of labels after update;
-` add-if-not-exists` — add label if it doesn't exist before in the list of labels of repository;
- `remove-if-not-applicable` — remove the label after update if it is not applicable anymore.

Combine all strategies if it is applicable using the list of strategies. Put the list of these options as a key `strategy` within a label. If the value is not set in the list the value of key is false. Example:

```yaml
"feature":
   files:
     added: src/**/*.html
   strategy:
     - add-if-not-exists
     - completely-update
```

```

2021-12-02 11:05 UTC, nlopin commented on README.md
> +## Comparison with other labelers
I think it makes sense as a separate document. In this one our main goal is to convince user why this action is great and how to configure it

2021-12-02 18:39 UTC, igsekor approved these changes

2021-12-02 18:39 UTC, merged